version: '3.9'
services:
  sql:
    image: postgres:13.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: jira_development # The PostgreSQL default database (automatically created at first launch
  app:
    build:
      context: ../
      dockerfile: ./docker/App/Dockerfile
    volumes:
      - ../client/:/app:rw
    ports:
      - '8080:8080'
    depends_on:
      sql:
        condition: service_started
      api:
        condition: service_started
    links:
      - sql
      - api
  api:
    build:
      context: ../
      dockerfile: ./docker/Api/Dockerfile
    volumes:
      - ../api/:/app:rw
    ports:
      - '3000:3000'
    depends_on:
      sql:
        condition: service_started
    links:
      - sql
